name: Build Agda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # agda-version: [2.6.2, 2.7.0]

    steps:
      - name: Cache cabal
        uses: actions/cache@v4
        with:
          path: ~/.cabal
          key: cabal-dir
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: 9.8.2
          cabal-version: 3.10.3.0
      - run: mkdir -p installdir
      - name: Install Agda
        run: cabal install --installdir installdir Agda
      - run: tar cvf agda.tar.gz -C "$(dirname $(dirname $(realpath installdir/agda)))" .
      - uses: actions/upload-artifact@v4
        with:
          name: agda.tar.gz
          path: agda.tar.gz